<a href="https://colab.research.google.com/github/BrightmanMT/Pytorch-Tutorial-Youtube/blob/main/intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [1]:
import torch
import numpy as np

**LIST**

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY**

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.20627569, 0.22473661, 0.7974835 , 0.58606977],
       [0.49026285, 0.74604648, 0.64838562, 0.74160171],
       [0.8411538 , 0.38088121, 0.99330396, 0.84273105]])

In [4]:
np1.dtype

dtype('float64')

**TENSOR**

In [5]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.6816, 0.4432, 0.6841, 0.0459],
        [0.0025, 0.0628, 0.2081, 0.0173],
        [0.5391, 0.1839, 0.1422, 0.5654]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## create a tensor out of my nupmy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2063, 0.2247, 0.7975, 0.5861],
        [0.4903, 0.7460, 0.6484, 0.7416],
        [0.8412, 0.3809, 0.9933, 0.8427]], dtype=torch.float64)