<a href="https://colab.research.google.com/github/BrightmanMT/Pytorch-Tutorial-Youtube/blob/main/intro_to_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

**LIST**

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY**

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.20627569, 0.22473661, 0.7974835 , 0.58606977],
       [0.49026285, 0.74604648, 0.64838562, 0.74160171],
       [0.8411538 , 0.38088121, 0.99330396, 0.84273105]])

In [4]:
np1.dtype

dtype('float64')

**TENSOR**

In [5]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.6816, 0.4432, 0.6841, 0.0459],
        [0.0025, 0.0628, 0.2081, 0.0173],
        [0.5391, 0.1839, 0.1422, 0.5654]])

In [6]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
## create a tensor out of my nupmy
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2063, 0.2247, 0.7975, 0.5861],
        [0.4903, 0.7460, 0.6484, 0.7416],
        [0.8412, 0.3809, 0.9933, 0.8427]], dtype=torch.float64)

In [10]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
#Reshape if we dont know the number of iterms using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# view
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
#with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch6 = my_torch5.reshape(2,-1)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch5[1]= 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [25]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [27]:
#slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#grab a specific item
my_torch7[7]

tensor(7)

In [29]:
# Grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [30]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [31]:
#return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

**MATH OPERATIONS IN TENSOR**

In [33]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [36]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [37]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [39]:
#subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [40]:
#subtraction longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [41]:
#Mul
tensor_b * tensor_a

tensor([ 5, 12, 21, 32])

In [44]:
# Mul longhand

torch.mul(tensor_b, tensor_a)

tensor([ 5, 12, 21, 32])

In [46]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [47]:
#Division longhand

torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [48]:
#Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [49]:
#Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [51]:
# Exponential
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [52]:
# Another way to write longhand

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [53]:
#Reassignment
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [54]:
tensor_a

tensor([ 6,  8, 10, 12])